[circle]
1 = "â‘ "
2 = "â‘¡"
3 = "â‘¢"
4 = "â‘£"
5 = "â‘¤"
6 = "â‘¥"
7 = "â‘¦"
8 = "â‘§"
9 = "â‘¨"
- = "âŠ–"
"=" = "âŠœ"
q = "â“ "
w = "â“¦"
e = "â“”"
r = "â“¡"
t = "â“£"
y = "â“¨"
u = "â“¤"
i = "â“˜"
o = "â“"
p = "â“Ÿ"
"\\" = "â¦¸"
a = "â“"
s = "â“¢"
d = "â““"
f = "â“•"
g = "â“–"
h = "â“—"
j = "â“™"
k = "â“š"
l = "â“›"
z = "â“©"
x = "â“§"
c = "â“’"
v = "â“¥"
b = "â“‘"
n = "â“"
m = "â“œ"
"." = "â¨€"
"/" = "âŠ˜"
"*" = "âŠ›"
"+" = "âŠ•"
Q = "â“†"
W = "â“Œ"
E = "â’º"
R = "â“‡"
T = "â“‰"
Y = "â“"
U = "â“Š"
I = "â’¾"
O = "â“„"
P = "â“…"
"|" = "â¦¶"
A = "â’¶"
S = "â“ˆ"
D = "â’¹"
F = "â’»"
G = "â’¼"
H = "â’½"
J = "â’¿"
K = "â“€"
L = "â“"
Z = "â“"
X = "â“"
C = "â’¸"
V = "â“‹"
B = "â’·"
N = "â“ƒ"
M = "â“‚"
"<" = "â§€"
">" = "â§"

[negative_circle]
0 = "â“¿"
Q = "ğŸ… "
W = "ğŸ…¦"
E = "ğŸ…”"
R = "ğŸ…¡"
T = "ğŸ…£"
Y = "ğŸ…¨"
U = "ğŸ…¤"
I = "ğŸ…˜"
O = "ğŸ…"
P = "ğŸ…Ÿ"
A = "ğŸ…"
S = "ğŸ…¢"
D = "ğŸ…“"
F = "ğŸ…•"
G = "ğŸ…–"
H = "ğŸ…—"
J = "ğŸ…™"
K = "ğŸ…š"
L = "ğŸ…›"
Z = "ğŸ…©"
X = "ğŸ…§"
C = "ğŸ…’"
V = "ğŸ…¥"
B = "ğŸ…‘"
N = "ğŸ…"
M = "ğŸ…œ"

[monospace]
"`" = "ï½€"
1 = "ï¼‘"
2 = "ï¼’"
3 = "ï¼“"
4 = "ï¼”"
5 = "ï¼•"
6 = "ï¼–"
7 = "ï¼—"
8 = "ï¼˜"
9 = "ï¼™"
0 = "ï¼"
- = "ï¼"
"=" = "ï¼"
q = "ï½‘"
w = "ï½—"
e = "ï½…"
r = "ï½’"
t = "ï½”"
y = "ï½™"
u = "ï½•"
i = "ï½‰"
o = "ï½"
p = "ï½"
"[" = "ï¼»"
"]" = "ï¼½"
"\\" = "ï¼¼"
a = "ï½"
s = "ï½“"
d = "ï½„"
f = "ï½†"
g = "ï½‡"
h = "ï½ˆ"
j = "ï½Š"
k = "ï½‹"
l = "ï½Œ"
";" = "ï¼›"
"'" = "ï¼‡"
z = "ï½š"
x = "ï½˜"
c = "ï½ƒ"
v = "ï½–"
b = "ï½‚"
n = "ï½"
m = "ï½"
"," = "ï¼Œ"
"." = "ï¼"
"/" = "ï¼"
"~" = "ï½"
"!" = "ï¼"
"@" = "ï¼ "
"#" = "ï¼ƒ"
"$" = "ï¼„"
"%" = "ï¼…"
"^" = "ï¼¾"
"&" = "ï¼†"
"*" = "ï¼Š"
"(" = "ï¼ˆ"
")" = "ï¼‰"
_ = "ï¼¿"
"+" = "ï¼‹"
Q = "ï¼±"
W = "ï¼·"
E = "ï¼¥"
R = "ï¼²"
T = "ï¼´"
Y = "ï¼¹"
U = "ï¼µ"
I = "ï¼©"
O = "ï¼¯"
P = "ï¼°"
"{" = "ï½›"
"}" = "ï½"
"|" = "ï½œ"
A = "ï¼¡"
S = "ï¼³"
D = "ï¼¤"
F = "ï¼¦"
G = "ï¼§"
H = "ï¼¨"
J = "ï¼ª"
K = "ï¼«"
L = "ï¼¬"
":" = "ï¼š"
Z = "ï¼º"
X = "ï¼¸"
C = "ï¼£"
V = "ï¼¶"
B = "ï¼¢"
N = "ï¼®"
M = "ï¼­"
"?" = "ï¼Ÿ"

[math_bold]
1 = "ğŸ"
2 = "ğŸ"
3 = "ğŸ‘"
4 = "ğŸ’"
5 = "ğŸ“"
6 = "ğŸ”"
7 = "ğŸ•"
8 = "ğŸ–"
9 = "ğŸ—"
0 = "ğŸ"
q = "ğª"
w = "ğ°"
e = "ğ"
r = "ğ«"
t = "ğ­"
y = "ğ²"
u = "ğ®"
i = "ğ¢"
o = "ğ¨"
p = "ğ©"
a = "ğš"
s = "ğ¬"
d = "ğ"
f = "ğŸ"
g = "ğ "
h = "ğ¡"
j = "ğ£"
k = "ğ¤"
l = "ğ¥"
z = "ğ³"
x = "ğ±"
c = "ğœ"
v = "ğ¯"
b = "ğ›"
n = "ğ§"
m = "ğ¦"
Q = "ğ"
W = "ğ–"
E = "ğ„"
R = "ğ‘"
T = "ğ“"
Y = "ğ˜"
U = "ğ”"
I = "ğˆ"
O = "ğ"
P = "ğ"
A = "ğ€"
S = "ğ’"
D = "ğƒ"
F = "ğ…"
G = "ğ†"
H = "ğ‡"
J = "ğ‰"
K = "ğŠ"
L = "ğ‹"
Z = "ğ™"
X = "ğ—"
C = "ğ‚"
V = "ğ•"
B = "ğ"
N = "ğ"
M = "ğŒ"

[math_bold_fraktur]
q = "ğ––"
w = "ğ–œ"
e = "ğ–Š"
r = "ğ–—"
t = "ğ–™"
y = "ğ–"
u = "ğ–š"
i = "ğ–"
o = "ğ–”"
p = "ğ–•"
a = "ğ–†"
s = "ğ–˜"
d = "ğ–‰"
f = "ğ–‹"
g = "ğ–Œ"
h = "ğ–"
j = "ğ–"
k = "ğ–"
l = "ğ–‘"
z = "ğ–Ÿ"
x = "ğ–"
c = "ğ–ˆ"
v = "ğ–›"
b = "ğ–‡"
n = "ğ–“"
m = "ğ–’"
Q = "ğ•¼"
W = "ğ–‚"
E = "ğ•°"
R = "ğ•½"
T = "ğ•¿"
Y = "ğ–„"
U = "ğ–€"
I = "ğ•´"
O = "ğ•º"
P = "ğ•»"
A = "ğ•¬"
S = "ğ•¾"
D = "ğ•¯"
F = "ğ•±"
G = "ğ•²"
H = "ğ•³"
J = "ğ•µ"
K = "ğ•¶"
L = "ğ•·"
Z = "ğ–…"
X = "ğ–ƒ"
C = "ğ•®"
V = "ğ–"
B = "ğ•­"
N = "ğ•¹"
M = "ğ•¸"

[math_bold_italic]
q = "ğ’’"
w = "ğ’˜"
e = "ğ’†"
r = "ğ’“"
t = "ğ’•"
y = "ğ’š"
u = "ğ’–"
i = "ğ’Š"
o = "ğ’"
p = "ğ’‘"
a = "ğ’‚"
s = "ğ’”"
d = "ğ’…"
f = "ğ’‡"
g = "ğ’ˆ"
h = "ğ’‰"
j = "ğ’‹"
k = "ğ’Œ"
l = "ğ’"
z = "ğ’›"
x = "ğ’™"
c = "ğ’„"
v = "ğ’—"
b = "ğ’ƒ"
n = "ğ’"
m = "ğ’"
Q = "ğ‘¸"
W = "ğ‘¾"
E = "ğ‘¬"
R = "ğ‘¹"
T = "ğ‘»"
Y = "ğ’€"
U = "ğ‘¼"
I = "ğ‘°"
O = "ğ‘¶"
P = "ğ‘·"
A = "ğ‘¨"
S = "ğ‘º"
D = "ğ‘«"
F = "ğ‘­"
G = "ğ‘®"
H = "ğ‘¯"
J = "ğ‘±"
K = "ğ‘²"
L = "ğ‘³"
Z = "ğ’"
X = "ğ‘¿"
C = "ğ‘ª"
V = "ğ‘½"
B = "ğ‘©"
N = "ğ‘µ"
M = "ğ‘´"

[math_bold_script]
q = "ğ“º"
w = "ğ”€"
e = "ğ“®"
r = "ğ“»"
t = "ğ“½"
y = "ğ”‚"
u = "ğ“¾"
i = "ğ“²"
o = "ğ“¸"
p = "ğ“¹"
a = "ğ“ª"
s = "ğ“¼"
d = "ğ“­"
f = "ğ“¯"
g = "ğ“°"
h = "ğ“±"
j = "ğ“³"
k = "ğ“´"
l = "ğ“µ"
z = "ğ”ƒ"
x = "ğ”"
c = "ğ“¬"
v = "ğ“¿"
b = "ğ“«"
n = "ğ“·"
m = "ğ“¶"
Q = "ğ“ "
W = "ğ“¦"
E = "ğ“”"
R = "ğ“¡"
T = "ğ“£"
Y = "ğ“¨"
U = "ğ“¤"
I = "ğ“˜"
O = "ğ“"
P = "ğ“Ÿ"
A = "ğ“"
S = "ğ“¢"
D = "ğ““"
F = "ğ“•"
G = "ğ“–"
H = "ğ“—"
J = "ğ“™"
K = "ğ“š"
L = "ğ“›"
Z = "ğ“©"
X = "ğ“§"
C = "ğ“’"
V = "ğ“¥"
B = "ğ“‘"
N = "ğ“"
M = "ğ“œ"

[math_double_struck]
1 = "ğŸ™"
2 = "ğŸš"
3 = "ğŸ›"
4 = "ğŸœ"
5 = "ğŸ"
6 = "ğŸ"
7 = "ğŸŸ"
8 = "ğŸ "
9 = "ğŸ¡"
0 = "ğŸ˜"
q = "ğ•¢"
w = "ğ•¨"
e = "ğ•–"
r = "ğ•£"
t = "ğ•¥"
y = "ğ•ª"
u = "ğ•¦"
i = "ğ•š"
o = "ğ• "
p = "ğ•¡"
a = "ğ•’"
s = "ğ•¤"
d = "ğ••"
f = "ğ•—"
g = "ğ•˜"
h = "ğ•™"
j = "ğ•›"
k = "ğ•œ"
l = "ğ•"
z = "ğ•«"
x = "ğ•©"
c = "ğ•”"
v = "ğ•§"
b = "ğ•“"
n = "ğ•Ÿ"
m = "ğ•"
Q = "â„š"
W = "ğ•"
E = "ğ”¼"
R = "â„"
T = "ğ•‹"
Y = "ğ•"
U = "ğ•Œ"
I = "ğ•€"
O = "ğ•†"
P = "â„™"
A = "ğ”¸"
S = "ğ•Š"
D = "ğ”»"
F = "ğ”½"
G = "ğ”¾"
H = "â„"
J = "ğ•"
K = "ğ•‚"
L = "ğ•ƒ"
Z = "â„¤"
X = "ğ•"
C = "â„‚"
V = "ğ•"
B = "ğ”¹"
N = "â„•"
M = "ğ•„"

[math_monospace]
1 = "ğŸ·"
2 = "ğŸ¸"
3 = "ğŸ¹"
4 = "ğŸº"
5 = "ğŸ»"
6 = "ğŸ¼"
7 = "ğŸ½"
8 = "ğŸ¾"
9 = "ğŸ¿"
0 = "ğŸ¶"
q = "ğšš"
w = "ğš "
e = "ğš"
r = "ğš›"
t = "ğš"
y = "ğš¢"
u = "ğš"
i = "ğš’"
o = "ğš˜"
p = "ğš™"
a = "ğšŠ"
s = "ğšœ"
d = "ğš"
f = "ğš"
g = "ğš"
h = "ğš‘"
j = "ğš“"
k = "ğš”"
l = "ğš•"
z = "ğš£"
x = "ğš¡"
c = "ğšŒ"
v = "ğšŸ"
b = "ğš‹"
n = "ğš—"
m = "ğš–"
Q = "ğš€"
W = "ğš†"
E = "ğ™´"
R = "ğš"
T = "ğšƒ"
Y = "ğšˆ"
U = "ğš„"
I = "ğ™¸"
O = "ğ™¾"
P = "ğ™¿"
A = "ğ™°"
S = "ğš‚"
D = "ğ™³"
F = "ğ™µ"
G = "ğ™¶"
H = "ğ™·"
J = "ğ™¹"
K = "ğ™º"
L = "ğ™»"
Z = "ğš‰"
X = "ğš‡"
C = "ğ™²"
V = "ğš…"
B = "ğ™±"
N = "ğ™½"
M = "ğ™¼"

[math_sans]
1 = "ğŸ£"
2 = "ğŸ¤"
3 = "ğŸ¥"
4 = "ğŸ¦"
5 = "ğŸ§"
6 = "ğŸ¨"
7 = "ğŸ©"
8 = "ğŸª"
9 = "ğŸ«"
0 = "ğŸ¢"
q = "ğ—Š"
w = "ğ—"
e = "ğ–¾"
r = "ğ—‹"
t = "ğ—"
y = "ğ—’"
u = "ğ—"
i = "ğ—‚"
o = "ğ—ˆ"
p = "ğ—‰"
a = "ğ–º"
s = "ğ—Œ"
d = "ğ–½"
f = "ğ–¿"
g = "ğ—€"
h = "ğ—"
j = "ğ—ƒ"
k = "ğ—„"
l = "ğ—…"
z = "ğ—“"
x = "ğ—‘"
c = "ğ–¼"
v = "ğ—"
b = "ğ–»"
n = "ğ—‡"
m = "ğ—†"
Q = "ğ–°"
W = "ğ–¶"
E = "ğ–¤"
R = "ğ–±"
T = "ğ–³"
Y = "ğ–¸"
U = "ğ–´"
I = "ğ–¨"
O = "ğ–®"
P = "ğ–¯"
A = "ğ– "
S = "ğ–²"
D = "ğ–£"
F = "ğ–¥"
G = "ğ–¦"
H = "ğ–§"
J = "ğ–©"
K = "ğ–ª"
L = "ğ–«"
Z = "ğ–¹"
X = "ğ–·"
C = "ğ–¢"
V = "ğ–µ"
B = "ğ–¡"
N = "ğ–­"
M = "ğ–¬"

[math_sans_bold]
1 = "ğŸ­"
2 = "ğŸ®"
3 = "ğŸ¯"
4 = "ğŸ°"
5 = "ğŸ±"
6 = "ğŸ²"
7 = "ğŸ³"
8 = "ğŸ´"
9 = "ğŸµ"
0 = "ğŸ¬"
q = "ğ—¾"
w = "ğ˜„"
e = "ğ—²"
r = "ğ—¿"
t = "ğ˜"
y = "ğ˜†"
u = "ğ˜‚"
i = "ğ—¶"
o = "ğ—¼"
p = "ğ—½"
a = "ğ—®"
s = "ğ˜€"
d = "ğ—±"
f = "ğ—³"
g = "ğ—´"
h = "ğ—µ"
j = "ğ—·"
k = "ğ—¸"
l = "ğ—¹"
z = "ğ˜‡"
x = "ğ˜…"
c = "ğ—°"
v = "ğ˜ƒ"
b = "ğ—¯"
n = "ğ—»"
m = "ğ—º"
Q = "ğ—¤"
W = "ğ—ª"
E = "ğ—˜"
R = "ğ—¥"
T = "ğ—§"
Y = "ğ—¬"
U = "ğ—¨"
I = "ğ—œ"
O = "ğ—¢"
P = "ğ—£"
A = "ğ—”"
S = "ğ—¦"
D = "ğ——"
F = "ğ—™"
G = "ğ—š"
H = "ğ—›"
J = "ğ—"
K = "ğ—"
L = "ğ—Ÿ"
Z = "ğ—­"
X = "ğ—«"
C = "ğ—–"
V = "ğ—©"
B = "ğ—•"
N = "ğ—¡"
M = "ğ— "

[math_sans_bold_italic]
q = "ğ™¦"
w = "ğ™¬"
e = "ğ™š"
r = "ğ™§"
t = "ğ™©"
y = "ğ™®"
u = "ğ™ª"
i = "ğ™"
o = "ğ™¤"
p = "ğ™¥"
a = "ğ™–"
s = "ğ™¨"
d = "ğ™™"
f = "ğ™›"
g = "ğ™œ"
h = "ğ™"
j = "ğ™Ÿ"
k = "ğ™ "
l = "ğ™¡"
z = "ğ™¯"
x = "ğ™­"
c = "ğ™˜"
v = "ğ™«"
b = "ğ™—"
n = "ğ™£"
m = "ğ™¢"
Q = "ğ™Œ"
W = "ğ™’"
E = "ğ™€"
R = "ğ™"
T = "ğ™"
Y = "ğ™”"
U = "ğ™"
I = "ğ™„"
O = "ğ™Š"
P = "ğ™‹"
A = "ğ˜¼"
S = "ğ™"
D = "ğ˜¿"
F = "ğ™"
G = "ğ™‚"
H = "ğ™ƒ"
J = "ğ™…"
K = "ğ™†"
L = "ğ™‡"
Z = "ğ™•"
X = "ğ™“"
C = "ğ˜¾"
V = "ğ™‘"
B = "ğ˜½"
N = "ğ™‰"
M = "ğ™ˆ"

[math_sans_italic]
q = "ğ˜²"
w = "ğ˜¸"
e = "ğ˜¦"
r = "ğ˜³"
t = "ğ˜µ"
y = "ğ˜º"
u = "ğ˜¶"
i = "ğ˜ª"
o = "ğ˜°"
p = "ğ˜±"
a = "ğ˜¢"
s = "ğ˜´"
d = "ğ˜¥"
f = "ğ˜§"
g = "ğ˜¨"
h = "ğ˜©"
j = "ğ˜«"
k = "ğ˜¬"
l = "ğ˜­"
z = "ğ˜»"
x = "ğ˜¹"
c = "ğ˜¤"
v = "ğ˜·"
b = "ğ˜£"
n = "ğ˜¯"
m = "ğ˜®"
Q = "ğ˜˜"
W = "ğ˜"
E = "ğ˜Œ"
R = "ğ˜™"
T = "ğ˜›"
Y = "ğ˜ "
U = "ğ˜œ"
I = "ğ˜"
O = "ğ˜–"
P = "ğ˜—"
A = "ğ˜ˆ"
S = "ğ˜š"
D = "ğ˜‹"
F = "ğ˜"
G = "ğ˜"
H = "ğ˜"
J = "ğ˜‘"
K = "ğ˜’"
L = "ğ˜“"
Z = "ğ˜¡"
X = "ğ˜Ÿ"
C = "ğ˜Š"
V = "ğ˜"
B = "ğ˜‰"
N = "ğ˜•"
M = "ğ˜”"

[parenthesized]
1 = "â‘´"
2 = "â‘µ"
3 = "â‘¶"
4 = "â‘·"
5 = "â‘¸"
6 = "â‘¹"
7 = "â‘º"
8 = "â‘»"
9 = "â‘¼"
q = "â’¬"
w = "â’²"
e = "â’ "
r = "â’­"
t = "â’¯"
y = "â’´"
u = "â’°"
i = "â’¤"
o = "â’ª"
p = "â’«"
a = "â’œ"
s = "â’®"
d = "â’Ÿ"
f = "â’¡"
g = "â’¢"
h = "â’£"
j = "â’¥"
k = "â’¦"
l = "â’§"
z = "â’µ"
x = "â’³"
c = "â’"
v = "â’±"
b = "â’"
n = "â’©"
m = "â’¨"

[square]
- = "âŠŸ"
"\\" = "â§…"
"." = "âŠ¡"
"/" = "â§„"
"*" = "â§†"
"+" = "âŠ"
Q = "ğŸ…€"
W = "ğŸ…†"
E = "ğŸ„´"
R = "ğŸ…"
T = "ğŸ…ƒ"
Y = "ğŸ…ˆ"
U = "ğŸ…„"
I = "ğŸ„¸"
O = "ğŸ„¾"
P = "ğŸ„¿"
A = "ğŸ„°"
S = "ğŸ…‚"
D = "ğŸ„³"
F = "ğŸ„µ"
G = "ğŸ„¶"
H = "ğŸ„·"
J = "ğŸ„¹"
K = "ğŸ„º"
L = "ğŸ„»"
Z = "ğŸ…‰"
X = "ğŸ…‡"
C = "ğŸ„²"
V = "ğŸ……"
B = "ğŸ„±"
N = "ğŸ„½"
M = "ğŸ„¼"

[negative_square]
Q = "ğŸ†€"
W = "ğŸ††"
E = "ğŸ…´"
R = "ğŸ†"
T = "ğŸ†ƒ"
Y = "ğŸ†ˆ"
U = "ğŸ†„"
I = "ğŸ…¸"
O = "ğŸ…¾"
P = "ğŸ…¿"
A = "ğŸ…°"
S = "ğŸ†‚"
D = "ğŸ…³"
F = "ğŸ…µ"
G = "ğŸ…¶"
H = "ğŸ…·"
J = "ğŸ…¹"
K = "ğŸ…º"
L = "ğŸ…»"
Z = "ğŸ†‰"
X = "ğŸ†‡"
C = "ğŸ…²"
V = "ğŸ†…"
B = "ğŸ…±"
N = "ğŸ…½"
M = "ğŸ…¼"

[cute]
w = "áºƒ"
e = "Ã©"
r = "Å•"
y = "Ó³"
u = "Ãº"
i = "Ã­"
o = "Å‘"
p = "á¹•"
a = "Ã¡"
s = "Å›"
g = "Çµ"
k = "á¸±"
l = "Äº"
z = "Åº"
c = "Ä‡"
n = "Å„"
m = "á¸¿"
W = "áº‚"
E = "Ã‰"
R = "Å”"
Y = "Ó²"
U = "Å°"
O = "Å"
P = "á¹”"
A = "Ã"
G = "Ç´"
K = "á¸°"
L = "Ä¹"
Z = "Å¹"
C = "Ä†"
N = "Åƒ"
M = "á¸¾"

[math_fraktur]
q = "ğ”®"
w = "ğ”´"
e = "ğ”¢"
r = "ğ”¯"
t = "ğ”±"
y = "ğ”¶"
u = "ğ”²"
i = "ğ”¦"
o = "ğ”¬"
p = "ğ”­"
a = "ğ”"
s = "ğ”°"
d = "ğ”¡"
f = "ğ”£"
g = "ğ”¤"
h = "ğ”¥"
j = "ğ”§"
k = "ğ”¨"
l = "ğ”©"
z = "ğ”·"
x = "ğ”µ"
c = "ğ” "
v = "ğ”³"
b = "ğ”Ÿ"
n = "ğ”«"
m = "ğ”ª"
Q = "ğ””"
W = "ğ”š"
E = "ğ”ˆ"
R = "â„œ"
T = "ğ”—"
Y = "ğ”œ"
U = "ğ”˜"
I = "â„‘"
O = "ğ”’"
P = "ğ”“"
A = "ğ”„"
S = "ğ”–"
D = "ğ”‡"
F = "ğ”‰"
G = "ğ”Š"
H = "â„Œ"
J = "ğ”"
K = "ğ”"
L = "ğ”"
Z = "â„¨"
X = "ğ”›"
C = "â„­"
V = "ğ”™"
B = "ğ”…"
N = "ğ”‘"
M = "ğ”"

[rock_dots]
3 = "ÓŸ"
- = "â¸š"
w = "áº…"
e = "Ã«"
r = "á¹›"
t = "áº—"
y = "Ã¿"
u = "Ã¼"
i = "Ã¯"
o = "Ã¶"
p = "á¹—"
a = "Ã¤"
s = "á¹¡"
d = "á¸‹"
f = "á¸Ÿ"
g = "Ä¡"
h = "á¸§"
k = "á¸³"
l = "á¸·"
z = "Å¼"
x = "áº"
c = "Ä‹"
v = "á¹¿"
b = "á¸…"
n = "á¹…"
m = "á¹"
"." = "âˆµ"
W = "áº„"
E = "Ğ"
R = "á¹š"
T = "á¹ª"
Y = "Å¸"
U = "Ãœ"
I = "Ğ‡"
O = "Ã–"
P = "á¹–"
A = "Ã„"
S = "á¹ "
D = "á¸Š"
F = "á¸"
G = "Ä "
H = "á¸¦"
K = "á¸²"
L = "á¸¶"
Z = "Å»"
X = "áºŒ"
C = "ÄŠ"
V = "á¹¾"
B = "á¸„"
N = "á¹„"
M = "á¹€"

[small_caps]
w = "á´¡"
e = "á´‡"
r = "Ê€"
t = "á´›"
u = "á´œ"
i = "Éª"
o = "á´"
p = "á´©"
a = "á´€"
s = "êœ±"
d = "á´…"
f = "êœ°"
g = "É¢"
h = "Êœ"
j = "á´Š"
k = "á´‹"
l = "ÊŸ"
z = "á´¢"
c = "á´„"
v = "á´ "
b = "Ê™"
n = "É´"
m = "á´"

[stroked]
2 = "Æ»"
q = "ê—"
e = "É‡"
r = "É"
t = "Å§"
y = "É"
u = "áµ¾"
i = "É¨"
o = "Ã¸"
p = "áµ½"
d = "Ä‘"
g = "Ç¥"
h = "Ä§"
j = "É‰"
k = "ê"
l = "Å‚"
z = "Æ¶"
c = "È¼"
b = "Æ€"
Q = "ê–"
E = "É†"
R = "ÉŒ"
T = "Å¦"
Y = "É"
I = "Æ—"
O = "Ã˜"
P = "â±£"
A = "Èº"
D = "Ä"
G = "Ç¤"
H = "Ä¦"
J = "Éˆ"
K = "ê€"
L = "Å"
Z = "Æµ"
C = "È»"
B = "Éƒ"

[subscript]
1 = "â‚"
2 = "â‚‚"
3 = "â‚ƒ"
4 = "â‚„"
5 = "â‚…"
6 = "â‚†"
7 = "â‚‡"
8 = "â‚ˆ"
9 = "â‚‰"
0 = "â‚€"
e = "â‚‘"
r = "áµ£"
t = "â‚œ"
u = "áµ¤"
i = "áµ¢"
o = "â‚’"
p = "â‚š"
a = "â‚"
s = "â‚›"
h = "â‚•"
j = "â±¼"
k = "â‚–"
l = "â‚—"
x = "â‚“"
v = "áµ¥"
n = "â‚™"
m = "â‚˜"

[superscript]
1 = "Â¹"
2 = "Â²"
3 = "Â³"
4 = "â´"
5 = "âµ"
6 = "â¶"
7 = "â·"
8 = "â¸"
9 = "â¹"
0 = "â°"
w = "Ê·"
e = "áµ‰"
r = "Ê³"
t = "áµ—"
y = "Ê¸"
u = "áµ˜"
i = "â±"
o = "áµ’"
p = "áµ–"
a = "áµƒ"
s = "Ë¢"
d = "áµˆ"
f = "á¶ "
g = "áµ"
h = "Ê°"
j = "Ê²"
k = "áµ"
l = "Ë¡"
z = "á¶»"
x = "Ë£"
c = "á¶œ"
v = "áµ›"
b = "áµ‡"
n = "â¿"
m = "áµ"
W = "áµ‚"
E = "á´±"
R = "á´¿"
T = "áµ€"
U = "áµ"
I = "á´µ"
O = "á´¼"
P = "á´¾"
A = "á´¬"
D = "á´°"
G = "á´³"
H = "á´´"
J = "á´¶"
K = "á´·"
L = "á´¸"
V = "â±½"
B = "á´®"
N = "á´º"
M = "á´¹"

[inverted]
q = "b"
w = "Ê"
e = "Ç"
r = "É¹"
t = "Ê‡"
y = "Ê"
u = "n"
i = "Ä±"
p = "d"
a = "É"
d = "p"
f = "ÉŸ"
g = "Æƒ"
h = "É¥"
j = "É¾"
k = "Ê"
l = "×Ÿ"
"'" = ","
c = "É”"
v = "ÊŒ"
b = "q"
n = "u"
m = "É¯"
"," = "â€˜"
"!" = "Â¡"
"&" = "â…‹"
V = "ğŒ¡"
"?" = "Â¿"

[reversed]
1 = "ß"
q = "p"
e = "É˜"
p = "q"
s = "ê™…"
d = "b"
";" = "â"
c = "â†„"
b = "d"
"~" = "âˆ½"
E = "Æ"
R = "á´™"
P = "êŸ¼"
S = "ê™„"
F = "êŸ»"
L = "â…ƒ"
C = "â†ƒ"
N = "á´"
"?" = "â¸®"
