[Circled]
a = "â“"
b = "â“‘"
c = "â“’"
d = "â““"
e = "â“”"
f = "â“•"
g = "â“–"
h = "â“—"
i = "â“˜"
j = "â“™"
k = "â“š"
l = "â“›"
m = "â“œ"
n = "â“"
o = "â“"
p = "â“Ÿ"
q = "â“ "
r = "â“¡"
s = "â“¢"
t = "â“£"
u = "â“¤"
v = "â“¥"
w = "â“¦"
x = "â“§"
y = "â“¨"
z = "â“©"
1 = "â‘ "
2 = "â‘¡"
3 = "â‘¢"
4 = "â‘£"
5 = "â‘¤"
6 = "â‘¥"
7 = "â‘¦"
8 = "â‘§"
9 = "â‘¨"
0 = "0"

["Negative circled"]
a = "ğŸ…"
b = "ğŸ…‘"
c = "ğŸ…’"
d = "ğŸ…“"
e = "ğŸ…”"
f = "ğŸ…•"
g = "ğŸ…–"
h = "ğŸ…—"
i = "ğŸ…˜"
j = "ğŸ…™"
k = "ğŸ…š"
l = "ğŸ…›"
m = "ğŸ…œ"
n = "ğŸ…"
o = "ğŸ…"
p = "ğŸ…Ÿ"
q = "ğŸ… "
r = "ğŸ…¡"
s = "ğŸ…¢"
t = "ğŸ…£"
u = "ğŸ…¤"
v = "ğŸ…¥"
w = "ğŸ…¦"
x = "ğŸ…§"
y = "ğŸ…¨"
z = "ğŸ…©"
0 = "â“¿"
